project:
  type: book
  output-dir: _prep

# quarto publish netlify --no-render
# quarto publish netlify --no-browser --no-prompt
# quarto publish netlify --no-render --no-browser --no-prompt

execute:
  eval: true
  echo: false
  error: false
  warning: false
  message: false  # not sure if allowed
  note: false  # not sure if allowed
  freeze: auto  # during global project renders, re-render only when source changes
  
editor_options:
  chunk_output_type: console

format:
  html:
    theme: cosmo
    fig-width: 11
    fig-height: 6
  # pdf:
  #   documentclass: scrreprt

book:
  title: "CUNY slides prep"
  author: "Don Boyd"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - data_prep.qmd
    - interest_rates.qmd
    - equity_like_investments.qmd
    - ufl_pct_gdp.qmd
    - uflgdp_vs_fr.qmd
    - treadwater.qmd

